[theme]
base = "light"
primaryColor = "#256D85"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#E0E0E0"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[client]
toolbarMode = "minimal"
